version: "3"
services:
  
  streamer:
    build: 
      context: "."
      args:
        UID: "${UID}"
        GID: "${GID}"
    image: "streaming:0.1.0"
    user: "${UID}:${GID}"
    command: ["stream", "/videos/ocean.mp4", "1920x1012"]
    volumes:
    - ".:/videos:rw"

  player:
    build: 
      context: "."
      args:
        UID: "${UID}"
        GID: "${GID}"
    image: "streaming:0.1.0"
    user: "${UID}:${GID}"
    command: ["play", "--zmq-socket-address=tcp://streamer:5557" ,"1920x1012"]
    depends_on:
    - streamer
    environment:
      DISPLAY: "${DISPLAY}"
    volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/dev/dri:/dev/dri"