version: "3"
services:

  broker:
    build: "./broker"
    image: "broker:0.1.0"
    ports:
    - 12345:12345
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
    - ".:/broker/docker-compose:ro"
    environment:
      UID: "${UID}"
      GID: "${GID}"
      DISPLAY: "${DISPLAY}"
    devices:
    - /dev/dri:/dev/dr
  
  streamer:
    build: 
      context: "./streamer"
      args:
        UID: "${UID}"
        GID: "${GID}"
    image: "streamer:0.1.0"
    user: "${UID}:${GID}"
    depends_on:
    - broker
    environment:
      DBUS_ADDRESS: "tcp:host=broker,port=12345"

  player:
    build:
      context: "./player"
      args:
        UID: "${UID}"
        GID: "${GID}"
    image: "player:0.1.0"
    user: "${UID}:${GID}"
    depends_on:
    - broker
    - streamer
    environment:
      DBUS_ADDRESS: "tcp:host=broker,port=12345"
      DISPLAY: "${DISPLAY}"
    volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"